### ISSUE TITLE
fwalker

### ISSUE THREAD

**Issue by FancyZhang96** [AlanConstantine/10FoldCrossValidation#1]
请问fwalker包您还有吗，在您给的链接中没有找到，谢谢。

**Comment by AlanConstantine** [comment]
https://github.com/AlanConstantine/SomeUsefulPyFile

**Comment by AlanConstantine** [comment]
> 请问fwalker包您还有吗，在您给的链接中没有找到，谢谢。

https://github.com/AlanConstantine/SomeUsefulPyFile
